name = "pinthop-api"
main = "backend/dist/worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "pinthop-api-production"
routes = ["api.pinthop.com/*", "pinthop.com/api/*"]

[env.staging]
name = "pinthop-api-staging"
routes = ["staging-api.pinthop.com/*"]

# Environment variables (set these in Cloudflare dashboard)
# MONGODB_URI
# JWT_SECRET
# CORS_ORIGIN

# Remove build command since we'll build manually
# [build]
# command = "npm run build:worker"
# cwd = "backend"

[dev]
port = 8787
local_protocol = "http"