name = "pinthop-api"
main = "src/worker-secure.ts"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "production"
CORS_ORIGIN = "https://67515bf9.pinthop.pages.dev"

# 環境変数の定義
# 実際の値はCloudflare Dashboardで設定します
# wrangler secret put JWT_SECRET
# wrangler secret put MONGODB_URI
# wrangler secret put TEST_USER_1_USERNAME
# wrangler secret put TEST_USER_1_PASSWORD
# wrangler secret put TEST_USER_1_EMAIL
# wrangler secret put TEST_USER_2_USERNAME
# wrangler secret put TEST_USER_2_PASSWORD
# wrangler secret put TEST_USER_2_EMAIL
# wrangler secret put TEST_USER_3_USERNAME
# wrangler secret put TEST_USER_3_PASSWORD
# wrangler secret put TEST_USER_3_EMAIL

[[compatibility_flags]]
nodejs_compat = true